<?php
namespace Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\FormEvent;
use Symfony\Component\Form\FormEvents;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;
use Transformer\GridFSFileToFile;
use Transformer\StringToArray;

class Configuration extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        parent::buildForm($builder, $options);
        $builder
            ->add("title", "text")
            ->add('subtitle', 'text')
            ->add('description', 'textarea', array('attr' => array('rows' => 3)))
            ->add('contactEmail', 'text', array('required' => false))
            ->add('twitterUsername', 'text', array('required' => false))
            ->add('googleSiteVerification', 'text', array('required' => true, 'data' => '057nzccyBOntpG9lqhwOZ1s9NfpOPzS29h308SFqeNo'))
            ->add('facebookAppId', 'text', array('required' => true, 'data' => "849201731760693"))
            ->add('language', 'choice', array('label' => "Default Language",
                'choices' => array('en' => 'English', 'ru' => 'Russian')));
    }


    /**
     * Returns the name of this type.
     *
     * @return string The name of this type
     */
    public function getName()
    {
        return "configuration";
    }

    /*  public function setDefaultOptions(OptionsResolverInterface $resolver)
      {
          parent::setDefaultOptions($resolver); // TODO: Change the autogenerated stub
          $resolver->setDefaults(array(
              'data_class' => '\Entity\Image'
          ));
      }*/


}