<?php
namespace Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\FormEvent;
use Symfony\Component\Form\FormEvents;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;
use Transformer\LinksToJsonString;

/**
 * Class Menu
 * build a menu form
 * links are serialized and deserialized into a json string
 * @package Form
 */
class Menu extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options) {
        parent::buildForm($builder, $options);
        $builder
            ->add("title", "text")
            ->add('isPublished', 'choice', array('choices' => array('no', 'yes'), "data" => "yes"))
            ->add('description', 'textarea')
            ->add(
                $builder->create('links', 'hidden', array(
                    'attr' => array('ng-model' => 'menu_links')))
                    ->addModelTransformer(new LinksToJsonString())
            );
    }


    /**
     * Returns the name of this type.
     *
     * @return string The name of this type
     */
    public function getName() {
        return "menu";
    }

    public function setDefaultOptions(OptionsResolverInterface $resolver) {
        parent::setDefaultOptions($resolver); // TODO: Change the autogenerated stub
        $resolver->setDefaults(array(
            'data_class' => '\Entity\Menu'
        ));
    }
}